@startuml
Browser -> "Multimedia API": Multipart upload
"Multimedia API" -> Postgres: store metadata
"Multimedia API" -> Minio: Multipart upload
Minio --> "Multimedia API": status
"Multimedia API" --> Browser: status
"Multimedia API" -> Postgres: upload done (success or error)
"Multimedia API" --> Browser: upload done (success or error)
@enduml
